server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          username: budandin
          password: 790730090.
          uri: https://gitee.com/budandin/tensquare_dev.git
  rabbitmq:
    host: 192.168.80.128
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh